export const MACHINE_URL = '/Compelet_Machine_Model_Textures/Machine_Model_Textures/Lottery_Simulator13.glb';
export const BALL_URL = '/Compelet_Machine_Model_Textures/Ball_Model_Textures/Ball_Mdl_001.glb';

export const MGPE_URL = import.meta.env.VITE_REACT_APP_MGPE;
export const MGPE_TOKEN = import.meta.env.VITE_REACT_APP_MGPE_AUTH_TOKEN;
export const RABBIT_WS = import.meta.env.VITE_REACT_APP_RABBITMQ_WS;
export const RABBIT_TOPIC = import.meta.env.VITE_REACT_APP_RABBITMQ_STOMP_TOPIC;
export const RABBIT_USER = import.meta.env.VITE_REACT_APP_RABBITMQ_USER;
export const RABBIT_PASS = import.meta.env.VITE_REACT_APP_RABBITMQ_PASS;
export const RABBIT_HOST = import.meta.env.VITE_REACT_APP_RABBITMQ_HOST;
export const PROTO_PATH = ['/protos/GameResult.proto', '/protos/GameEnquery.proto', '/protos/GameStart.proto', '/protos/GameStop.proto'];

export const Control_Ball_Index = 0;

// pipeCenterPath.js
import * as THREE from 'three';

export const PIPE_CENTER_POINTS = [
  new THREE.Vector3(-0.091, 1.0132, -0.0703),
  new THREE.Vector3(-0.091, 1.1532, -0.0653),
  new THREE.Vector3(-0.091, 1.2832, 0.0053),
  new THREE.Vector3(-0.091, 1.2932, 0.2053),
  new THREE.Vector3(-0.0976, 1.1727, 0.4697),
  new THREE.Vector3(-0.0976, 0.9027, 0.7497),
  new THREE.Vector3(-0.1309, 0.6354, 0.9376),
  new THREE.Vector3(-0.2031, 0.3203, 1.0593),
  new THREE.Vector3(-0.249, -0.0045, 1.0933),
  new THREE.Vector3(-0.2885, -0.3296, 1.0901),
  new THREE.Vector3(-0.2536, -0.6566, 0.9736),
  new THREE.Vector3(-0.192 + 0.5, -0.9898, 0.7343),
  new THREE.Vector3(-0.1929 + 0.5, -1.269, 0.3407),
  new THREE.Vector3(-0.26 + 0.5, -1.4492, -0.1193),
  new THREE.Vector3(-0.2989 + 0.5, -1.5592, -0.5193),
  new THREE.Vector3(-0.3277 + 0.5, -1.6688, -0.9962),
];

export const responseCodeList = [
  { responseCode: 200, message: 'Success' },
  { responseCode: 500, message: 'System Error' },
  { responseCode: 202, message: 'Missing Header' },
  { responseCode: 208, message: 'Duplicated transaction ID' },
  { responseCode: 209, message: 'Decrypt Message Failed' },
  { responseCode: 301, message: 'Unsupported Game Type' },
  { responseCode: 330, message: 'Barcode incorrect' },
  { responseCode: 347, message: 'Not A Winning Ticket' },
  { responseCode: 348, message: 'Ticket Not Found' },
  { responseCode: 349, message: 'Waiting Draw Result' },
  { responseCode: 6000, message: 'Parse Request Failed' },
  { responseCode: 6001, message: 'Duplicated transaction ID' },
  { responseCode: 6020, message: 'Reference No. Invalid' },
  { responseCode: 6030, message: 'No Draw Result' },
  { responseCode: 6040, message: 'Insufficient Balance' },
  { responseCode: 6050, message: 'Payment Failed' },
  { responseCode: 6060, message: 'MAC Error' },
  { responseCode: 6070, message: 'Under Reversal' },
  { responseCode: 6080, message: 'Ticket Cancelled' },
  { responseCode: 6090, message: 'Purchase PIN error' },
  { responseCode: 6120, message: 'Package File Not Exist' },
  { responseCode: 6130, message: 'Enquiry Package File Error' },
  { responseCode: 6140, message: 'File Not Exist' },
  { responseCode: 4120, message: 'Record Not Exist' },
  { responseCode: 4130, message: 'Game Instance Not Exist' },
  { responseCode: 4140, message: 'Game Not Exist' },
  { responseCode: 4500, message: 'Invalid Account or PIN' },
  { responseCode: 4501, message: 'Security Answer Incorrect' },
  { responseCode: 4510, message: 'Account Used' },
  { responseCode: 4511, message: 'Email Used' },
  { responseCode: 4520, message: 'Account Already Activeated' },
  { responseCode: 4530, message: 'Invalid Account or PIN' },
  { responseCode: 4540, message: 'Insufficient Balance' },
  { responseCode: 4550, message: 'Invalid Account or PIN' },
  { responseCode: 4560, message: 'Cashout Pass Too Many Attempt. Account Locked' },
  { responseCode: 4570, message: 'Invalid Account or PIN' },
  { responseCode: 4580, message: 'Account Frozen' },
  { responseCode: 4590, message: 'Cashout Pass Error' },
  { responseCode: 4600, message: 'Account Locked' },
  { responseCode: 4610, message: 'Referene No. Invalid' },
  { responseCode: 4620, message: 'No Active Cashout Pass' },
  { responseCode: 4630, message: 'No Active Cashout Pass' },
  { responseCode: 4640, message: 'Topup TE Exception' },
  { responseCode: 4650, message: 'Insufficient Balance for SMS' },
  { responseCode: 4660, message: 'Register Fail' },
  { responseCode: 4710, message: 'Security Answer Incorrect' },
  { responseCode: 4720, message: 'Too Many Attempts. User Cannot Register Today' },
  { responseCode: 4730, message: 'Too Many Attempts. User Cannot Recovery PIN Today' },
  { responseCode: 4740, message: 'Logo Not Exist' },
  { responseCode: 4830, message: 'Language Not Supported' },
  { responseCode: 4840, message: 'APP URL Not Exist' },
  { responseCode: 4850, message: 'Email Not Modified' },
  { responseCode: 4860, message: 'Email Already Activated' },
  { responseCode: 4870, message: 'Email Not Modified' },
  { responseCode: 4880, message: 'Security Question Not Set' },
  { responseCode: 4890, message: 'Third Party Key Error' },
  { responseCode: 4900, message: 'Transaction Was Succeeded' },
  { responseCode: 4910, message: 'Duplicated Seq. No.' },
  { responseCode: 4920, message: 'Seq. No. Error' },
  { responseCode: 4930, message: 'No Marketing Info' },
  { responseCode: 64120, message: 'Record Not Exist' },
  { responseCode: 64130, message: 'Game Instance Not Exist' },
  { responseCode: 64140, message: 'Game Not Exist' },
  { responseCode: 64500, message: 'Invalid Account or PIN' },
  { responseCode: 64501, message: 'Security Answer Incorrect' },
  { responseCode: 64510, message: 'Account Used' },
  { responseCode: 64511, message: 'Email Used' },
  { responseCode: 64520, message: 'Account Already Activeated' },
  { responseCode: 64530, message: 'Invalid Account or PIN' },
  { responseCode: 64540, message: 'Insufficient Balance' },
  { responseCode: 64550, message: 'Invalid Account or PIN' },
  { responseCode: 64560, message: 'Cashout Pass Too Many Attempt. Account Locked' },
  { responseCode: 64570, message: 'Invalid Account or PIN' },
  { responseCode: 64580, message: 'Account Frozen' },
  { responseCode: 64590, message: 'Cashout Pass Error' },
  { responseCode: 64600, message: 'Account Locked' },
  { responseCode: 64610, message: 'Referene No. Invalid' },
  { responseCode: 64620, message: 'No Active Cashout Pass' },
  { responseCode: 64630, message: 'No Active Cashout Pass' },
  { responseCode: 64640, message: 'Topup TE Exception' },
  { responseCode: 64650, message: 'Insufficient Balance for SMS' },
  { responseCode: 64660, message: 'Register Fail' },
  { responseCode: 64710, message: 'Security Answer Incorrect' },
  { responseCode: 64720, message: 'Too Many Attempts. User Cannot Register Today' },
  { responseCode: 64730, message: 'Too Many Attempts. User Cannot Recovery PIN Today' },
  { responseCode: 64740, message: 'Logo Not Exist' },
  { responseCode: 64830, message: 'Language Not Supported' },
  { responseCode: 64840, message: 'APP URL Not Exist' },
  { responseCode: 64850, message: 'Email Not Modified' },
  { responseCode: 64860, message: 'Email Already Activated' },
  { responseCode: 64870, message: 'Email Not Modified' },
  { responseCode: 64880, message: 'Security Question Not Set' },
  { responseCode: 64890, message: 'Third Party Key Error' },
  { responseCode: 64900, message: 'Transaction Was Succeeded' },
  { responseCode: 64910, message: 'Duplicated Seq. No.' },
  { responseCode: 64920, message: 'Seq. No. Error' },
  { responseCode: 64930, message: 'No Marketing Info' },
  { responseCode: 63100, message: 'Voucher Not Exist' },
  { responseCode: 63110, message: 'Invalie Voucher' },
  { responseCode: 63120, message: 'Used Voucher' },
  { responseCode: 63130, message: 'Expired Voucher' },
  { responseCode: 63140, message: 'Voucher Inactive' },
  { responseCode: 63150, message: 'Voucher Fail To Activate' },
  { responseCode: 65000, message: 'Total Amount Error' },
  { responseCode: 70000, message: 'Payment Type Not Supported' },
  { responseCode: 70010, message: 'Invalid Amount' },
  { responseCode: 70020, message: 'Login Expired' },
  { responseCode: 70030, message: 'Date Invalid' },
  { responseCode: 70040, message: 'Account Not Exist' },
  { responseCode: 70060, message: 'ID Not Exist' },
  { responseCode: 70070, message: 'MAC Error' },
  { responseCode: 80050, message: 'Insufficient Balance' },
];
